// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgILWUR3JImKAjAx0y-43bNy65OjqpIY',
    appId: '1:781052430424:web:c2462b9890705db7fa622d',
    messagingSenderId: '781052430424',
    projectId: 'library-practice-5dc0f',
    authDomain: 'library-practice-5dc0f.firebaseapp.com',
    storageBucket: 'library-practice-5dc0f.appspot.com',
    measurementId: 'G-0CC5VGZT7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPWTFwmzBEgGQkkrmTJXgDFiMCcKAHkc',
    appId: '1:781052430424:android:5f3dc9545df52acffa622d',
    messagingSenderId: '781052430424',
    projectId: 'library-practice-5dc0f',
    storageBucket: 'library-practice-5dc0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA50DpaJH_Xvx4kbaseaS9EIPy8jyLrYR8',
    appId: '1:781052430424:ios:c99f40b21f172afefa622d',
    messagingSenderId: '781052430424',
    projectId: 'library-practice-5dc0f',
    storageBucket: 'library-practice-5dc0f.appspot.com',
    iosBundleId: 'com.example.Flutter_Libraryt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA50DpaJH_Xvx4kbaseaS9EIPy8jyLrYR8',
    appId: '1:781052430424:ios:d7c4ae90d9b663a2fa622d',
    messagingSenderId: '781052430424',
    projectId: 'library-practice-5dc0f',
    storageBucket: 'library-practice-5dc0f.appspot.com',
    iosBundleId: 'com.example.Flutter_Libraryt.RunnerTests',
  );
}
